name: Linting

on:
  pull_requests:
    branches: [main]

jobs:
  run-linting:
    name: Run linting
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install linting dependencies
        run: pip install black flake8
      
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true